[package]
name = "perf-attributes"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
perf = ["perf-core/perf"]

[dependencies]
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
perf-core = { path = "../perf-core" }
